version: '3.8'
services:
  backend:
    build:
      context: .  
      dockerfile: backend/Dockerfile  
    ports:
      - "4000:4000"
    environment:
      - DENO_ENV=development
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketdb
    ports:
      - "5432:5432"